/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  static const String PINGFANG_SC_BOLD = 'PingFang-SC-Bold';
  static const String PINGFANG_SC_REGULAR = 'PingFang-SC-Regular';
}
